apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments
  namespace: default
  annotations:
    keel.sh/policy: "all"

spec:
  replicas: 2

  selector:
    matchLabels:
      app: comments

  template:
    metadata:
      labels:
        app: comments

    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: comments
                topologyKey: kubernetes.io/hostname

      containers:
        - name: comments
          image: damou/library-app-comments:def21b778224d8ee49d334e87d6a9b4d8b659285

          ports:
            - containerPort: 3000

          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: comments-secret
                  key: MONGODB_URI

            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: comments-secret
                  key: MONGODB_DATABASE

            - name: KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: comments-secret
                  key: KAFKA_USERNAME

            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: comments-secret
                  key: KAFKA_PASSWORD

            - name: PUBLIC_KEY_PATH
              valueFrom:
                configMapKeyRef:
                  name: comments-config
                  key: PUBLIC_KEY_PATH

            - name: OTEL_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: comments-config
                  key: OTEL_SERVICE_NAME

            - name: OTEL_SERVICE_VERSION
              valueFrom:
                configMapKeyRef:
                  name: comments-config
                  key: OTEL_SERVICE_VERSION

            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: comments-config
                  key: OTEL_EXPORTER_OTLP_ENDPOINT

            - name: KAFKA_MEMBER_EVENTS_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: comments-config
                  key: KAFKA_MEMBER_EVENTS_TOPIC

            - name: KAFKA_MEMBER_EVENTS_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: comments-config
                  key: KAFKA_MEMBER_EVENTS_GROUP_ID

            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: comments-config
                  key: KAFKA_BROKERS

            - name: KAFKA_SASL_MECHANISM
              valueFrom:
                configMapKeyRef:
                  name: comments-config
                  key: KAFKA_SASL_MECHANISM

            - name: KAFKA_CA_PATH
              valueFrom:
                configMapKeyRef:
                  name: comments-config
                  key: KAFKA_CA_PATH

          volumeMounts:
            - name: public-key
              mountPath: /app/keys/public_key.pem
              subPath: public_key.pem
              readOnly: true

            - name: kafka-ca
              mountPath: /app/certs/ca.pem
              subPath: ca.pem
              readOnly: true

          startupProbe:
            tcpSocket:
              port: 3000
            periodSeconds: 5
            failureThreshold: 12

          livenessProbe:
            tcpSocket:
              port: 3000
            periodSeconds: 30
            failureThreshold: 3

          readinessProbe:
            tcpSocket:
              port: 3000
            periodSeconds: 10
            failureThreshold: 3

      volumes:
        - name: public-key
          secret:
            secretName: comments-public-key

        - name: kafka-ca
          configMap:
            name: comments-kafka-ca