apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: comments
  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: comments

  endpoints:
    - port: http
      path: /metrics
      interval: 15s