image:
  repository: damou/library-app-notification
  tag: 5515b8dd7acbd8a21ebadefa32db16d620b7f17d
  pullPolicy: IfNotPresent

config:
  app:
    name: Notification
    env: local
    debug: "true"
    url: http://localhost

    locale: en
    fallbackLocale: en
    fakerLocale: en_US

  otel:
    tracesExporter: "otlp"
    endpoint: "http://alloy:4318"
    protocol: "http/protobuf"
    logsExporter: "none"
    metricsExporter: "none"
    bspMaxExportBatchSize: "1"
    tracesSampler: always_on
    phpAutoloadEnabled: "true"
    serviceName: "notification"
    bspScheduleDelay: "1000"

  log:
    channel: stack
    stack: single
    level: debug

  database:
    connection: pgsql
    host: ep-twilight-sunset-aom9ylam-pooler.c-2.ap-southeast-1.aws.neon.tech
    port: "5432"
    database: notification
    sslmode: require

  frontend:
    url: http://localhost:3000

  session:
    driver: "null"
    lifetime: "120"
    encrypt: "false"
    path: /
    domain: localhost

  cache:
    store: redis

  redis:
    client: phpredis
    host: notification-redis
    port: "6379"

  kafka:
    brokers: library-app-kafka-library-app.l.aivencloud.com:19687
    securityProtocol: SASL_SSL
    mechanisms: SCRAM-SHA-256
    caPath: /var/www/html/ca.pem
    compressionType: none
    debug: "true"

  broadcast:
    connection: log

  filesystem:
    disk: local

  queue:
    connection: "null"

  mail:
    mailer: resend
    fromAddress: no-reply@damou.dev
    fromName: Library App

  aws:
    region: us-east-1
    bucket: ""
    usePathStyleEndpoint: "false"

  cors:
    allowedOrigins: http://localhost:8080

resources:
  requests:
    cpu: 100m
    memory: 256Mi

  limits:
    cpu: 500m
    memory: 512Mi

redis:
  image: redis:8-alpine
  storage: 512Mi

  resources:
    requests:
      cpu: 50m
      memory: 64Mi

    limits:
      cpu: 250m
      memory: 256Mi

workers:
  - name: users
    artisanCommand: kafka:consume-users
    consumerGroup: notification-user-group
    replicas: 2

  - name: catalogue
    artisanCommand: kafka:consume-catalog
    consumerGroup: notification-catalogue-group
    replicas: 2

  - name: borrow
    artisanCommand: kafka:consume-borrow
    consumerGroup: notification-borrow-group
    replicas: 2

  - name: return
    artisanCommand: kafka:consume-return
    consumerGroup: notification-return-group
    replicas: 2