apiVersion: v1
kind: Service

metadata:
  name: library-frontend

spec:
  type: {{ .Values.service.type }}

  selector:
    app: library-frontend

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http