apiVersion: apps/v1
kind: Deployment
metadata:
  name: borrow
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: borrow
  template:
    metadata:
      labels:
        app: borrow
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: borrow
                topologyKey: kubernetes.io/hostname

      containers:
        - name: borrow
          image: damou/library-app-borrow:9387604fbcdea01192780cdc5eca4bb731626367

          volumeMounts:
            - name: public-key-volume
              mountPath: /etc/keys
              readOnly: true

            - name: kafka-aiven-ca
              mountPath: /app/ca.pem
              subPath: ca.pem
              readOnly: true

          ports:
            - containerPort: 8083

          envFrom:
            - configMapRef:
                name: borrow-config

            - secretRef:
                name: borrow-secret

          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "library-app-kafka-library-app.l.aivencloud.com:19687"

            - name: KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-aiven-secret
                  key: KAFKA_USERNAME

            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-aiven-secret
                  key: KAFKA_PASSWORD

            - name: KAFKA_CA_PATH
              value: "file:/app/ca.pem"

            - name: OTEL_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: borrow-config
                  key: OTEL_SERVICE_NAME

            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: borrow-config
                  key: OTEL_EXPORTER_OTLP_ENDPOINT

      volumes:
        - name: public-key-volume
          secret:
            secretName: auth-keys
            items:
              - key: public.pem
                path: public_key.pem

        - name: kafka-aiven-ca
          configMap:
            name: kafka-aiven-ca