image:
  repository: damou/library-app-frontend
  tag: "1.5.5"
  pullPolicy: IfNotPresent

replicas: 2

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 500m
    memory: 256Mi