apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth
  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: library-app-auth

  endpoints:
    - port: http
      path: /prometheus
      interval: 15s