apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kafka
  - auth
  - catalogue
  - borrow
  - inventory
  - analytics
  - membercard
  - comments
  - ingress
  - jaeger
  - records