apiVersion: v1
kind: Service
metadata:
  name: search-api
  labels:
    app: search-api
spec:
  type: ClusterIP

  selector:
    app: search-api

  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP